const INITIAL = {
  calls: [
    {id:'C-2026-01',title:'Intercambio académico 2026-II',direction:'SALIENTE',period:'2026-II',start:'2026-07-15',end:'2026-08-30',status:'ACTIVA',places:28,description:'Movilidad semestral en universidades con convenio vigente.'},
    {id:'C-2026-02',title:'Movilidad entrante internacional',direction:'ENTRANTE',period:'2026-II',start:'2026-06-01',end:'2026-09-15',status:'ACTIVA',places:40,description:'Recepción de estudiantes internacionales en la UNSAAC.'},
    {id:'C-2026-03',title:'Pasantías de investigación',direction:'SALIENTE',period:'2027-I',start:'2026-09-01',end:'2026-11-10',status:'BORRADOR',places:12,description:'Estancias cortas en centros de investigación asociados.'}
  ],
  applications: [
    {id:'SGMS-0261',direction:'SALIENTE',student:'María Quispe Huamán',code:'193847',faculty:'Ingeniería',destination:'Universidad de Granada',callId:'C-2026-01',status:'EN_REVISION_DOCUMENTAL',submitted:'2026-08-02',progress:72,documents:[{name:'DNI',status:'APROBADO'},{name:'Récord académico',status:'APROBADO'},{name:'Carta de motivación',status:'OBSERVADO'},{name:'Constancia de matrícula',status:'SUBIDO'}],history:[['POSTULADO','02 ago 2026'],['EN REVISIÓN DOCUMENTAL','04 ago 2026']]},
    {id:'SGMS-0262',direction:'SALIENTE',student:'José Huamán Ttito',code:'201122',faculty:'Ciencias Sociales',destination:'UNAM',callId:'C-2026-01',status:'OBSERVADO',submitted:'2026-08-03',progress:55,documents:[{name:'DNI',status:'APROBADO'},{name:'Récord académico',status:'OBSERVADO'},{name:'Carta de motivación',status:'APROBADO'}],history:[['POSTULADO','03 ago 2026'],['OBSERVADO','06 ago 2026']]},
    {id:'SGMS-0254',direction:'SALIENTE',student:'Carla Flores Nina',code:'188746',faculty:'Derecho',destination:'Universidad de Chile',callId:'C-2026-01',status:'APROBADO_OCRI',submitted:'2026-07-29',progress:100,documents:[{name:'DNI',status:'APROBADO'},{name:'Récord académico',status:'APROBADO'},{name:'Carta de motivación',status:'APROBADO'}],history:[['POSTULADO','29 jul 2026'],['APROBADO OCRI','05 ago 2026']]},
    {id:'SGME-0108',direction:'ENTRANTE',student:'Sofía Martínez Ruiz',code:'EXT-4491',faculty:'Arquitectura',destination:'Universidad de Granada · España',callId:'C-2026-02',status:'VALIDACION_ACADEMICA',submitted:'2026-07-25',progress:80,documents:[{name:'Pasaporte',status:'APROBADO'},{name:'Carta de nominación',status:'APROBADO'},{name:'Récord académico',status:'APROBADO'},{name:'Seguro internacional',status:'EN_REVISION'}],history:[['NOMINADO','18 jul 2026'],['POSTULACIÓN ENVIADA','25 jul 2026'],['VALIDACIÓN ACADÉMICA','06 ago 2026']]},
    {id:'SGME-0112',direction:'ENTRANTE',student:'Mateo Silva Costa',code:'EXT-4510',faculty:'Ciencias',destination:'Universidade de São Paulo · Brasil',callId:'C-2026-02',status:'OBSERVADO',submitted:'2026-08-01',progress:50,documents:[{name:'Pasaporte',status:'APROBADO'},{name:'Carta de nominación',status:'OBSERVADO'},{name:'Récord académico',status:'SUBIDO'}],history:[['NOMINADO','23 jul 2026'],['OBSERVADO','05 ago 2026']]}
  ],
  nominations:[{id:'NOM-026',student:'Sofía Martínez Ruiz',university:'Universidad de Granada',country:'España',email:'sofia.martinez@example.edu',status:'REGISTRO_COMPLETO'},{id:'NOM-031',student:'Mateo Silva Costa',university:'Universidade de São Paulo',country:'Brasil',email:'mateo.silva@example.edu',status:'POSTULACION_ENVIADA'},{id:'NOM-034',student:'Emma Dubois',university:'Université de Bordeaux',country:'Francia',email:'emma.dubois@example.edu',status:'INVITACION_ENVIADA'}]
};
const ROLES={admin:{name:'Ana Torres',label:'Administrador OCRI',initials:'AT'},reviewer:{name:'Luis Cárdenas',label:'Evaluador OCRI',initials:'LC'},student:{name:'María Quispe',label:'Alumno UNSAAC',initials:'MQ'},external:{name:'Sofía Martínez',label:'Estudiante externo',initials:'SM'}};
let state=load(); let session=null; let route='dashboard';
function load(){try{return JSON.parse(localStorage.getItem('sigma-data'))||structuredClone(INITIAL)}catch{return structuredClone(INITIAL)}}
function save(){localStorage.setItem('sigma-data',JSON.stringify(state))}
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function badge(status){const s=status.replaceAll('_',' ');const cls=/APROBADO|ACTIVA|COMPLETO|CONFIRMADO/.test(status)?'ok':/OBSERVADO|RECHAZADO/.test(status)?'bad':/REVISION|VALIDACION|ENVIADA|SUBIDO/.test(status)?'info':/PENDIENTE|BORRADOR|INVITACION/.test(status)?'warn':'neutral';return `<span class="badge ${cls}">${esc(s)}</span>`}
function login(){session=null;$('#app').innerHTML=`<main class="login-shell"><section class="login-brand"><div class="brand"><div class="seal">S</div><div><div class="brand-name">SIGMA OCRI</div><div class="brand-sub">UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO</div></div></div><div class="hero"><div class="eyebrow">Movilidad académica</div><h1>Conectamos talento<br>con el <span>mundo.</span></h1><p>Una plataforma integral para gestionar postulaciones, documentos, evaluaciones y experiencias de movilidad académica.</p></div><div class="module-pills"><span>SGMS · Movilidad saliente</span><span>SGME · Movilidad entrante</span><span>OCRI · Gestión institucional</span></div></section><section class="login-panel"><div class="login-box"><div class="eyebrow">Bienvenido</div><h2>Acceder a SIGMA</h2><p>Selecciona un perfil para explorar el prototipo funcional. En producción se reemplazará por autenticación institucional.</p><div class="role-grid">${Object.entries(ROLES).map(([k,r],i)=>`<button class="role-option" onclick="enter('${k}')"><span class="role-icon">${['⚙','✓','↗','↙'][i]}</span><span><strong>${r.label}</strong><br><small class="muted">Ingresar como ${r.name}</small></span></button>`).join('')}</div><p class="login-note">Entorno de demostración · No ingrese datos personales reales.</p></div></section></main>`}
function enter(role){session={role,...ROLES[role]};route='dashboard';render()}
function navItems(){if(session.role==='student')return [['dashboard','Resumen'],['sgms','Mi postulación'],['calls','Convocatorias'],['documents','Documentos']];if(session.role==='external')return [['dashboard','Resumen'],['sgme','Mi postulación'],['calls','Convocatorias'],['documents','Documentos']];return [['dashboard','Dashboard'],['calls','Convocatorias'],['sgms','Movilidad saliente'],['sgme','Movilidad entrante'],['nominations','Nominaciones'],['documents','Revisión documental'],['reports','Reportes']]}
function render(){if(!session)return login();const title=navItems().find(x=>x[0]===route)?.[1]||'SIGMA';$('#app').innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="seal">S</div><div><div class="brand-name">SIGMA OCRI</div><div class="brand-sub">UNSAAC</div></div></div><nav class="nav">${navItems().map(([r,l])=>`<button class="${r===route?'active':''}" onclick="go('${r}')"><span>${icons[r]||'•'}</span>${l}</button>`).join('')}</nav><div class="sidebar-foot"><div class="user-mini"><div class="avatar">${session.initials}</div><div><strong>${session.name}</strong><small>${session.label}</small></div></div><button class="logout" onclick="login()">Cerrar sesión</button></div></aside><main class="main"><header class="topbar"><div style="display:flex;gap:12px;align-items:center"><button class="icon-button mobile-menu" onclick="$('#sidebar').classList.toggle('open')">☰</button><h2>${title}</h2></div><div class="top-actions"><button class="icon-button" title="Notificaciones">🔔</button><span class="badge info">2026-II</span></div></header><section class="content" id="view"></section></main></div>`;views[route]?.();}
function go(r){route=r;render()}
const icons={dashboard:'▦',calls:'▤',sgms:'↗',sgme:'↙',nominations:'◎',documents:'□',reports:'▥'};
function head(title,desc,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div>${action}</div>`}
function filteredApps(dir){let a=state.applications.filter(x=>x.direction===dir);if(session.role==='student')a=a.filter(x=>x.code==='193847');if(session.role==='external')a=a.filter(x=>x.code==='EXT-4491');return a}
const views={
dashboard(){const apps=state.applications, pending=apps.filter(x=>/REVISION|VALIDACION/.test(x.status)).length, observed=apps.filter(x=>x.status==='OBSERVADO').length, approved=apps.filter(x=>/APROBADO/.test(x.status)).length;if(session.role==='student'||session.role==='external'){const a=filteredApps(session.role==='student'?'SALIENTE':'ENTRANTE')[0];$('#view').innerHTML=head(`Hola, ${session.name.split(' ')[0]}`,'Revisa el avance de tu proceso de movilidad.')+`<div class="cards"><div class="card stat"><div class="stat-label">Estado actual</div><div style="margin:16px 0">${badge(a.status)}</div><div class="progress"><span style="width:${a.progress}%"></span></div></div><div class="card stat"><div class="stat-label">Avance del expediente</div><div class="stat-value">${a.progress}%</div><div class="stat-change">Actualizado recientemente</div></div><div class="card stat"><div class="stat-label">Documentos aprobados</div><div class="stat-value">${a.documents.filter(d=>d.status==='APROBADO').length}/${a.documents.length}</div></div><div class="card stat"><div class="stat-label">Observaciones</div><div class="stat-value">${a.documents.filter(d=>d.status==='OBSERVADO').length}</div></div></div>${applicationDetail(a)}`;return}$('#view').innerHTML=head('Panel institucional','Resumen operativo de movilidad académica al 7 de agosto de 2026.',`<button class="btn btn-soft" onclick="resetDemo()">Restablecer demo</button>`)+`<div class="cards"><div class="card stat"><div class="stat-label">Postulaciones totales</div><div class="stat-value">${apps.length}</div><div class="stat-change">Periodo 2026-II</div></div><div class="card stat"><div class="stat-label">Pendientes de revisión</div><div class="stat-value">${pending}</div><div class="stat-change">Requieren atención</div></div><div class="card stat"><div class="stat-label">Expedientes observados</div><div class="stat-value">${observed}</div></div><div class="card stat"><div class="stat-label">Aprobados OCRI</div><div class="stat-value">${approved}</div></div></div><div class="grid-2"><div class="card"><div class="section-title"><h3>Actividad reciente</h3><button class="btn btn-sm btn-soft" onclick="go('documents')">Revisar</button></div>${appTable(apps.slice(0,5))}</div><div class="card"><h3>Distribución de movilidad</h3><div class="bar-chart"><div class="bar-col"><div class="bar" style="height:140px"></div>Saliente</div><div class="bar-col"><div class="bar" style="height:92px"></div>Entrante</div><div class="bar-col"><div class="bar" style="height:50px"></div>Aprobada</div><div class="bar-col"><div class="bar" style="height:72px"></div>Revisión</div></div></div></div>`},
calls(){const canEdit=/admin/.test(session.role);$('#view').innerHTML=head('Convocatorias','Oportunidades y periodos de movilidad académica.',canEdit?`<button class="btn btn-primary" onclick="callModal()">+ Nueva convocatoria</button>`:'')+`<div class="filters"><select class="input" onchange="filterCards(this.value)"><option value="">Todas las direcciones</option><option>SALIENTE</option><option>ENTRANTE</option></select></div><div class="call-grid" id="callGrid">${state.calls.map(c=>callCard(c,canEdit)).join('')}</div>`},
sgms(){appView('SALIENTE','SGMS · Movilidad saliente','Postulaciones de alumnos UNSAAC hacia universidades de destino.')},
sgme(){appView('ENTRANTE','SGME · Movilidad entrante','Postulaciones de estudiantes externos hacia la UNSAAC.')},
nominations(){const action=session.role==='admin'?`<button class="btn btn-primary" onclick="nominationModal()">+ Registrar nominación</button>`:'';$('#view').innerHTML=head('Nominaciones','Estudiantes propuestos por universidades de origen.',action)+`<div class="card">${nomTable()}</div>`},
documents(){let apps=state.applications;if(session.role==='student')apps=filteredApps('SALIENTE');if(session.role==='external')apps=filteredApps('ENTRANTE');const docs=apps.flatMap(a=>a.documents.map((d,i)=>({...d,app:a,index:i})));$('#view').innerHTML=head('Gestión documental','Revisión individual, observaciones y trazabilidad de documentos.')+`<div class="card"><div class="doc-list">${docs.map(d=>`<div class="doc-item"><div class="doc-icon">PDF</div><div class="doc-main"><strong>${esc(d.name)}</strong><small>${d.app.id} · ${esc(d.app.student)}</small></div>${badge(d.status)}${/admin|reviewer/.test(session.role)?`<button class="btn btn-sm btn-soft" onclick="reviewModal('${d.app.id}',${d.index})">Revisar</button>`:''}</div>`).join('')}</div></div>`},
reports(){const faculties={};state.applications.forEach(a=>faculties[a.faculty]=(faculties[a.faculty]||0)+1);$('#view').innerHTML=head('Reportes','Indicadores consolidados y exportación de información.',`<button class="btn btn-primary" onclick="exportCSV()">Exportar CSV</button>`)+`<div class="cards"><div class="card stat"><div class="stat-label">Salientes</div><div class="stat-value">${filteredApps('SALIENTE').length}</div></div><div class="card stat"><div class="stat-label">Entrantes</div><div class="stat-value">${filteredApps('ENTRANTE').length}</div></div><div class="card stat"><div class="stat-label">Universidades</div><div class="stat-value">5</div></div><div class="card stat"><div class="stat-label">Países</div><div class="stat-value">4</div></div></div><div class="grid-2"><div class="card"><h3>Postulantes por facultad</h3>${Object.entries(faculties).map(([f,n])=>`<p>${f} <strong style="float:right">${n}</strong></p><div class="progress"><span style="width:${n*30}%"></span></div>`).join('')}</div><div class="card"><h3>Estado de expedientes</h3>${state.applications.map(a=>`<p style="display:flex;justify-content:space-between"><span>${a.id}</span>${badge(a.status)}</p>`).join('')}</div></div>`}
};
function appView(dir,title,desc){const apps=filteredApps(dir);const action=(session.role==='student'&&dir==='SALIENTE')||(session.role==='external'&&dir==='ENTRANTE')?`<button class="btn btn-primary" onclick="applicationModal('${dir}')">+ Nueva postulación</button>`:'';$('#view').innerHTML=head(title,desc,action)+`<div class="cards"><div class="card stat"><div class="stat-label">Total</div><div class="stat-value">${apps.length}</div></div><div class="card stat"><div class="stat-label">En proceso</div><div class="stat-value">${apps.filter(a=>!/APROBADO|FINALIZADO/.test(a.status)).length}</div></div><div class="card stat"><div class="stat-label">Observados</div><div class="stat-value">${apps.filter(a=>a.status==='OBSERVADO').length}</div></div><div class="card stat"><div class="stat-label">Aprobados</div><div class="stat-value">${apps.filter(a=>/APROBADO/.test(a.status)).length}</div></div></div><div class="card">${apps.length?appTable(apps):'<div class="empty">No hay postulaciones registradas.</div>'}</div>`}
function appTable(apps){return `<div class="table-wrap"><table class="table"><thead><tr><th>Expediente</th><th>Estudiante</th><th>Facultad</th><th>Universidad</th><th>Estado</th><th>Avance</th><th></th></tr></thead><tbody>${apps.map(a=>`<tr><td><strong>${a.id}</strong><br><small class="muted">${a.submitted}</small></td><td>${esc(a.student)}<br><small class="muted">${a.code}</small></td><td>${esc(a.faculty)}</td><td>${esc(a.destination)}</td><td>${badge(a.status)}</td><td><div class="progress" style="width:75px"><span style="width:${a.progress}%"></span></div></td><td><button class="btn btn-sm btn-soft" onclick="detailModal('${a.id}')">Ver</button></td></tr>`).join('')}</tbody></table></div>`}
function applicationDetail(a){return `<div class="grid-2"><div class="card"><h3>Documentos del expediente</h3><div class="doc-list">${a.documents.map(d=>`<div class="doc-item"><div class="doc-icon">PDF</div><div class="doc-main"><strong>${esc(d.name)}</strong><small>Documento requerido</small></div>${badge(d.status)}</div>`).join('')}</div></div><div class="card"><h3>Seguimiento</h3><div class="timeline">${a.history.map(h=>`<div class="timeline-item"><div class="timeline-dot"></div><div><strong>${esc(h[0])}</strong><p>${h[1]}</p></div></div>`).join('')}</div></div></div>`}
function callCard(c,edit){return `<article class="call-card" data-direction="${c.direction}"><div class="call-top"></div><div class="call-body">${badge(c.status)} <span class="badge neutral">${c.direction}</span><h3>${esc(c.title)}</h3><p class="muted">${esc(c.description)}</p><div class="call-meta"><span>◷ ${c.start} — ${c.end}</span><span>▦ Periodo ${c.period} · ${c.places} vacantes</span></div><div class="call-actions"><button class="btn btn-sm btn-soft" onclick="toast('Requisitos: PDF, récord y carta de motivación')">Ver requisitos</button>${edit?`<button class="btn btn-sm btn-danger" onclick="removeCall('${c.id}')">Eliminar</button>`:''}</div></div></article>`}
function nomTable(){return `<div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Estudiante</th><th>Universidad</th><th>País</th><th>Contacto</th><th>Estado</th></tr></thead><tbody>${state.nominations.map(n=>`<tr><td><strong>${n.id}</strong></td><td>${esc(n.student)}</td><td>${esc(n.university)}</td><td>${esc(n.country)}</td><td>${esc(n.email)}</td><td>${badge(n.status)}</td></tr>`).join('')}</tbody></table></div>`}
function modal(body){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal">${body}</div></div>`)}function closeModal(){$('#modal')?.remove()}
function callModal(){modal(`<div class="modal-head"><h2>Nueva convocatoria</h2><button class="modal-close" onclick="closeModal()">×</button></div><form onsubmit="createCall(event)" class="form-grid"><div class="field wide"><label>Título</label><input class="input" name="title" required></div><div class="field"><label>Dirección</label><select class="input" name="direction"><option>SALIENTE</option><option>ENTRANTE</option></select></div><div class="field"><label>Periodo</label><input class="input" name="period" value="2027-I" required></div><div class="field"><label>Inicio</label><input class="input" type="date" name="start" required></div><div class="field"><label>Cierre</label><input class="input" type="date" name="end" required></div><div class="field"><label>Vacantes</label><input class="input" type="number" name="places" min="1" value="20"></div><div class="field wide"><label>Descripción</label><textarea class="input" name="description" required></textarea></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Guardar convocatoria</button></div></form>`)}
function createCall(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.calls.unshift({id:`C-${Date.now().toString().slice(-6)}`,...f,places:+f.places,status:'BORRADOR'});save();closeModal();render();toast('Convocatoria creada')}
function removeCall(id){if(!confirm('¿Eliminar esta convocatoria de demostración?'))return;state.calls=state.calls.filter(c=>c.id!==id);save();render();toast('Convocatoria eliminada')}
function filterCards(v){document.querySelectorAll('.call-card').forEach(e=>e.classList.toggle('hidden',v&&e.dataset.direction!==v))}
function detailModal(id){const a=state.applications.find(x=>x.id===id);modal(`<div class="modal-head"><div><h2>${a.id}</h2><span class="muted">${esc(a.student)}</span></div><button class="modal-close" onclick="closeModal()">×</button></div>${applicationDetail(a)}${/admin|reviewer/.test(session.role)?`<div class="modal-actions"><select id="appStatus" class="input"><option>EN_REVISION_DOCUMENTAL</option><option>OBSERVADO</option><option>APROBADO_OCRI</option><option>RECHAZADO</option><option>FINALIZADO</option></select><button class="btn btn-primary" onclick="changeAppStatus('${a.id}')">Actualizar estado</button></div>`:''}`)}
function changeAppStatus(id){const a=state.applications.find(x=>x.id===id),s=$('#appStatus').value;a.status=s;a.history.push([s.replaceAll('_',' '),new Date().toLocaleDateString('es-PE')]);a.progress=s==='APROBADO_OCRI'?100:a.progress;save();closeModal();render();toast('Estado actualizado y registrado')}
function reviewModal(id,index){const a=state.applications.find(x=>x.id===id),d=a.documents[index];modal(`<div class="modal-head"><h2>Revisar documento</h2><button class="modal-close" onclick="closeModal()">×</button></div><p><strong>${esc(d.name)}</strong><br><span class="muted">${a.id} · ${esc(a.student)}</span></p><div class="field"><label>Resultado</label><select class="input" id="docStatus"><option>APROBADO</option><option>OBSERVADO</option><option>RECHAZADO</option><option>EN_REVISION</option></select></div><div class="field" style="margin-top:14px"><label>Observación</label><textarea class="input" id="comment" placeholder="Detalle la observación si corresponde"></textarea></div><div class="modal-actions"><button class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="saveReview('${id}',${index})">Registrar revisión</button></div>`)}
function saveReview(id,i){const a=state.applications.find(x=>x.id===id),s=$('#docStatus').value;a.documents[i].status=s;a.documents[i].comment=$('#comment').value;a.documents[i].reviewedBy=session.name;a.documents[i].reviewedAt=new Date().toISOString();if(s==='OBSERVADO')a.status='OBSERVADO';save();closeModal();render();toast('Revisión guardada con trazabilidad')}
function nominationModal(){modal(`<div class="modal-head"><h2>Registrar nominación</h2><button class="modal-close" onclick="closeModal()">×</button></div><form class="form-grid" onsubmit="createNomination(event)"><div class="field wide"><label>Estudiante</label><input class="input" name="student" required></div><div class="field"><label>Universidad de origen</label><input class="input" name="university" required></div><div class="field"><label>País</label><input class="input" name="country" required></div><div class="field wide"><label>Correo institucional</label><input class="input" type="email" name="email" required></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Enviar invitación</button></div></form>`)}
function createNomination(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.nominations.unshift({id:`NOM-${String(state.nominations.length+35).padStart(3,'0')}`,...f,status:'INVITACION_ENVIADA'});save();closeModal();render();toast('Nominación registrada')}
function applicationModal(dir){modal(`<div class="modal-head"><h2>Nueva postulación ${dir==='SALIENTE'?'saliente':'entrante'}</h2><button class="modal-close" onclick="closeModal()">×</button></div><form class="form-grid" onsubmit="createApplication(event,'${dir}')"><div class="field wide"><label>Convocatoria</label><select class="input" name="callId">${state.calls.filter(c=>c.direction===dir&&c.status==='ACTIVA').map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></div><div class="field"><label>Facultad</label><input class="input" name="faculty" required></div><div class="field"><label>${dir==='SALIENTE'?'Universidad destino':'Universidad de origen'}</label><input class="input" name="destination" required></div><div class="field wide"><label>Motivación / actividad académica</label><textarea class="input" required></textarea></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Guardar borrador</button></div></form>`)}
function createApplication(e,dir){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),isOut=dir==='SALIENTE';state.applications.push({id:`${isOut?'SGMS':'SGME'}-${Date.now().toString().slice(-4)}`,direction:dir,student:session.name,code:isOut?'193847':'EXT-NEW',faculty:f.faculty,destination:f.destination,callId:f.callId,status:'BORRADOR',submitted:new Date().toISOString().slice(0,10),progress:15,documents:[{name:isOut?'DNI':'Pasaporte',status:'PENDIENTE'},{name:'Récord académico',status:'PENDIENTE'},{name:isOut?'Carta de motivación':'Carta de nominación',status:'PENDIENTE'}],history:[['BORRADOR',new Date().toLocaleDateString('es-PE')]]});save();closeModal();render();toast('Borrador creado')}
function exportCSV(){const rows=[['Expediente','Dirección','Estudiante','Facultad','Universidad','Estado','Fecha'],...state.applications.map(a=>[a.id,a.direction,a.student,a.faculty,a.destination,a.status,a.submitted])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='reporte-sigma.csv';a.click();URL.revokeObjectURL(a.href);toast('Reporte CSV generado')}
function resetDemo(){if(confirm('¿Restablecer todos los datos de la demostración?')){state=structuredClone(INITIAL);save();render();toast('Datos restablecidos')}}
login();
