import { createClient } from '@supabase/supabase-js';

// Cliente público: Supabase RLS limita cada operación según la sesión activa.
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;

// Datos temporales del prototipo; identidad, perfiles y roles ya viven en Supabase.
const INITIAL = {
  calls: [
    {id:'C-2026-01',title:'Intercambio académico 2026-II',direction:'SALIENTE',period:'2026-II',start:'2026-07-15',end:'2026-08-30',status:'ACTIVA',places:28,description:'Movilidad semestral en universidades con convenio vigente.'},
    {id:'C-2026-02',title:'Movilidad entrante internacional',direction:'ENTRANTE',period:'2026-II',start:'2026-06-01',end:'2026-09-15',status:'ACTIVA',places:40,description:'Recepción de estudiantes internacionales en la UNSAAC.'},
    {id:'C-2026-03',title:'Pasantías de investigación',direction:'SALIENTE',period:'2027-I',start:'2026-09-01',end:'2026-11-10',status:'BORRADOR',places:12,description:'Estancias cortas en centros de investigación asociados.'}
  ],
  applications: [
    {id:'SGMS-0261',direction:'SALIENTE',student:'María Quispe Huamán',code:'193847',faculty:'Ingeniería',destination:'Universidad de Granada',callId:'C-2026-01',status:'EN_REVISION_DOCUMENTAL',submitted:'2026-08-02',progress:72,documents:[{name:'DNI',status:'APROBADO'},{name:'Récord académico',status:'APROBADO'},{name:'Carta de motivación',status:'OBSERVADO'},{name:'Constancia de matrícula',status:'SUBIDO'}],history:[['POSTULADO','02 ago 2026'],['EN REVISIÓN DOCUMENTAL','04 ago 2026']]},
    {id:'SGMS-0262',direction:'SALIENTE',student:'José Huamán Ttito',code:'201122',faculty:'Ciencias Sociales',destination:'UNAM',callId:'C-2026-01',status:'OBSERVADO',submitted:'2026-08-03',progress:55,documents:[{name:'DNI',status:'APROBADO'},{name:'Récord académico',status:'OBSERVADO'},{name:'Carta de motivación',status:'APROBADO'}],history:[['POSTULADO','03 ago 2026'],['OBSERVADO','06 ago 2026']]},
    {id:'SGMS-0254',direction:'SALIENTE',student:'Carla Flores Nina',code:'188746',faculty:'Derecho',destination:'Universidad de Chile',callId:'C-2026-01',status:'APROBADO_OCRI',submitted:'2026-07-29',progress:100,documents:[{name:'DNI',status:'APROBADO'},{name:'Récord académico',status:'APROBADO'},{name:'Carta de motivación',status:'APROBADO'}],history:[['POSTULADO','29 jul 2026'],['APROBADO OCRI','05 ago 2026']]},
    {id:'SGME-0108',direction:'ENTRANTE',student:'Sofía Martínez Ruiz',code:'EXT-4491',faculty:'Arquitectura',destination:'Universidad de Granada · España',callId:'C-2026-02',status:'VALIDACION_ACADEMICA',submitted:'2026-07-25',progress:80,documents:[{name:'Pasaporte',status:'APROBADO'},{name:'Carta de nominación',status:'APROBADO'},{name:'Récord académico',status:'APROBADO'},{name:'Seguro internacional',status:'EN_REVISION'}],history:[['NOMINADO','18 jul 2026'],['POSTULACIÓN ENVIADA','25 jul 2026'],['VALIDACIÓN ACADÉMICA','06 ago 2026']]},
    {id:'SGME-0112',direction:'ENTRANTE',student:'Mateo Silva Costa',code:'EXT-4510',faculty:'Ciencias',destination:'Universidade de São Paulo · Brasil',callId:'C-2026-02',status:'OBSERVADO',submitted:'2026-08-01',progress:50,documents:[{name:'Pasaporte',status:'APROBADO'},{name:'Carta de nominación',status:'OBSERVADO'},{name:'Récord académico',status:'SUBIDO'}],history:[['NOMINADO','23 jul 2026'],['OBSERVADO','05 ago 2026']]}
  ],
  nominations:[{id:'NOM-026',student:'Sofía Martínez Ruiz',university:'Universidad de Granada',country:'España',email:'sofia.martinez@example.edu',status:'REGISTRO_COMPLETO'},{id:'NOM-031',student:'Mateo Silva Costa',university:'Universidade de São Paulo',country:'Brasil',email:'mateo.silva@example.edu',status:'POSTULACION_ENVIADA'},{id:'NOM-034',student:'Emma Dubois',university:'Université de Bordeaux',country:'Francia',email:'emma.dubois@example.edu',status:'INVITACION_ENVIADA'}]
};
// Los cuatro roles operativos aprobados para SIGMA.
const ROLE_LABELS={ADMIN_OCRI:'Administrador OCRI',ESTUDIANTE_UNSAAC:'Alumno UNSAAC',GESTOR_EXTERNO:'Gestor externo',ESTUDIANTE_EXTERNO:'Estudiante externo'};
const ROLE_VIEWS={ADMIN_OCRI:'admin',ESTUDIANTE_UNSAAC:'student',GESTOR_EXTERNO:'external_manager',ESTUDIANTE_EXTERNO:'external'};
let state=load(); let session=null; let route='dashboard'; let passwordRecoveryMode=false; let accessProfiles=[];
function load(){try{return JSON.parse(localStorage.getItem('sigma-data'))||structuredClone(INITIAL)}catch{return structuredClone(INITIAL)}}
function save(){localStorage.setItem('sigma-data',JSON.stringify(state))}
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function badge(status){const s=status.replaceAll('_',' ');const cls=/APROBADO|ACTIVA|COMPLETO|CONFIRMADO/.test(status)?'ok':/OBSERVADO|RECHAZADO/.test(status)?'bad':/REVISION|VALIDACION|ENVIADA|SUBIDO/.test(status)?'info':/PENDIENTE|BORRADOR|INVITACION/.test(status)?'warn':'neutral';return `<span class="badge ${cls}">${esc(s)}</span>`}
function login(){session=null;$('#app').innerHTML=`<main class="login-shell"><section class="login-brand"><div class="brand"><div class="seal">S</div><div><div class="brand-name">SIGMA OCRI</div><div class="brand-sub">UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO</div></div></div><div class="hero"><div class="eyebrow">Movilidad académica</div><h1>Conectamos talento<br>con el <span>mundo.</span></h1><p>Una plataforma integral para gestionar postulaciones, documentos, evaluaciones y experiencias de movilidad académica.</p></div><div class="module-pills"><span>SGMS · Movilidad saliente</span><span>SGME · Movilidad entrante</span><span>OCRI · Gestión institucional</span></div></section><section class="login-panel"><div class="login-box"><div class="eyebrow">Bienvenido</div><h2>Acceder a SIGMA</h2><p>Ingresa con el correo y la contraseña que configuraste al verificar tu cuenta.</p>${supabase?`<form class="role-grid" onsubmit="signIn(event)"><div class="field"><label>Correo</label><input class="input" name="email" type="email" autocomplete="email" placeholder="nombre@unsaac.edu.pe" required></div><div class="field"><label>Contraseña</label><input class="input" name="password" type="password" autocomplete="current-password" placeholder="Tu contraseña" required></div><button class="btn btn-primary" type="submit">Iniciar sesión</button><button class="btn btn-soft" type="button" onclick="requestPasswordReset()">Olvidé mi contraseña</button></form><button class="btn btn-gold" style="width:100%;margin-top:4px" onclick="showRegister()">Crear mi cuenta</button><p class="login-note">La verificación por enlace se usa solo al crear una cuenta o recuperar la contraseña.</p>`:`<p class="login-note">Falta la configuración local de Supabase. Copie <code>.env.example</code> a <code>.env.local</code> antes de iniciar la aplicación.</p>`}</div></section></main>`}
// Acceso ordinario: solo correo y contraseña; el enlace se reserva para verificar o recuperar.
async function signIn(event){event.preventDefault();const f=Object.fromEntries(new FormData(event.target));const {error}=await supabase.auth.signInWithPassword({email:f.email,password:f.password});if(error)toast('Correo o contraseña incorrectos.')}
async function requestPasswordReset(){const email=document.querySelector('[name="email"]')?.value?.trim();if(!email)return toast('Ingrese primero su correo.');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});toast(error?error.message:'Enlace de recuperación enviado. Revise su correo de pruebas.');}
function showRegister(){modal(`<div class="modal-head"><h2>Crear mi cuenta</h2><button class="modal-close" onclick="closeModal()">×</button></div><p class="muted">Verificaremos que el correo le pertenece. Después del enlace podrá crear su contraseña personal.</p><form class="form-grid" onsubmit="register(event)"><div class="field wide"><label>Nombre completo</label><input class="input" name="fullName" required></div><div class="field wide"><label>Correo institucional o universitario</label><input class="input" name="email" type="email" required></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Enviar verificación</button></div></form>`)}
async function register(event){event.preventDefault();const f=Object.fromEntries(new FormData(event.target));const {data:approved,error:domainError}=await supabase.rpc('is_registration_domain_approved',{candidate_email:f.email});if(domainError)return toast('No fue posible validar el dominio institucional.');if(!approved)return toast('No puede registrarse: necesita un correo de una universidad con asociación o convenio vigente con UNSAAC.');const {error}=await supabase.auth.signInWithOtp({email:f.email,options:{shouldCreateUser:true,data:{full_name:f.fullName},emailRedirectTo:window.location.origin}});if(error)return toast(error.message);closeModal();toast('Enlace de verificación enviado. Revise el correo de pruebas.');}
function passwordSetup(){const recovery=passwordRecoveryMode;$('#app').innerHTML=`<main class="login-shell"><section class="login-brand"><div class="brand"><div class="seal">S</div><div><div class="brand-name">SIGMA OCRI</div><div class="brand-sub">UNSAAC</div></div></div><div class="hero"><div class="eyebrow">Cuenta verificada</div><h1>Protege tu<br><span>acceso.</span></h1><p>Tu correo ya fue verificado. Define una contraseña personal para los próximos ingresos.</p></div></section><section class="login-panel"><div class="login-box"><div class="eyebrow">${recovery?'Recuperación':'Último paso'}</div><h2>${recovery?'Nueva contraseña':'Crea tu contraseña'}</h2><p>Usarás esta contraseña junto con tu correo en los siguientes accesos.</p><form class="role-grid" onsubmit="setPassword(event)"><div class="field"><label>Nueva contraseña</label><input class="input" name="password" type="password" autocomplete="new-password" minlength="8" required></div><div class="field"><label>Confirmar contraseña</label><input class="input" name="confirmation" type="password" autocomplete="new-password" minlength="8" required></div><button class="btn btn-primary" type="submit">Guardar contraseña</button></form></div></section></main>`}
async function setPassword(event){event.preventDefault();const f=Object.fromEntries(new FormData(event.target));if(f.password!==f.confirmation)return toast('Las contraseñas no coinciden.');const {error}=await supabase.auth.updateUser({password:f.password});if(error)return toast(error.message);const {error:profileError}=await supabase.from('profiles').update({password_configured_at:new Date().toISOString()}).eq('user_id',session.userId);if(profileError)return toast(profileError.message);passwordRecoveryMode=false;const {data:{user}}=await supabase.auth.getUser();if(user)await loadSession(user);toast('Contraseña configurada correctamente.');}
async function signOut(){await supabase.auth.signOut();login();toast('Sesión cerrada')}
async function loadSession(user){const [{data:profileResult,error:profileError},{data:roleResult,error:roleError}]=await Promise.all([supabase.from('profiles').select('full_name,status,email,password_configured_at,universities(name)').eq('user_id',user.id).single(),supabase.from('user_roles').select('roles(code,name)').eq('user_id',user.id).limit(1)]);if(profileError){toast(`No se pudo cargar el perfil: ${profileError.message}`);return login()}if(roleError){toast(`No se pudo cargar el rol: ${roleError.message}`);return login()}const roleCode=roleResult?.[0]?.roles?.code;const fullName=profileResult.full_name||user.user_metadata?.full_name||user.email;session={userId:user.id,email:user.email,name:fullName,label:roleCode?ROLE_LABELS[roleCode]:`Cuenta ${profileResult.status.toLowerCase()}`,initials:fullName.split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase(),role:ROLE_VIEWS[roleCode]||'pending',status:profileResult.status,university:profileResult.universities?.name||null};if(passwordRecoveryMode||!profileResult.password_configured_at)return passwordSetup();route='dashboard';render()}
function navItems(){if(session.role==='student')return [['General','dashboard','Resumen'],['SGMS · Saliente','sgms','Mi postulación'],['SGMS · Saliente','calls','Convocatorias'],['SGMS · Saliente','documents','Documentos']];if(session.role==='external')return [['General','dashboard','Resumen'],['SGME · Entrante','sgme','Mi postulación'],['SGME · Entrante','calls','Convocatorias'],['SGME · Entrante','documents','Documentos']];if(session.role==='external_manager')return [['General','dashboard','Resumen'],['SGME · Mi universidad','nominations','Nominaciones'],['SGME · Mi universidad','sgme','Postulaciones nominadas']];return [['General','dashboard','Panel general'],['SGMS · Movilidad saliente','calls','Convocatorias'],['SGMS · Movilidad saliente','sgms','Postulaciones salientes'],['SGME · Movilidad entrante','sgme','Postulaciones entrantes'],['SGME · Movilidad entrante','nominations','Nominaciones externas'],['Administración OCRI','access','Accesos y universidades'],['Administración OCRI','documents','Revisión documental'],['Administración OCRI','reports','Reportes']]}
function render(){if(!session)return login();if(session.role==='pending'){return accessPending()}const items=navItems(),title=items.find(x=>x[1]===route)?.[2]||'SIGMA',groups=Object.groupBy(items,x=>x[0]);const navigation=Object.entries(groups).map(([section,entries])=>`<div class="nav-group"><div class="nav-group-title">${section}</div>${entries.map(([,r,l])=>`<button class="${r===route?'active':''}" onclick="go('${r}')"><span>${icons[r]||'•'}</span>${l}</button>`).join('')}</div>`).join('');$('#app').innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="seal">S</div><div><div class="brand-name">SIGMA OCRI</div><div class="brand-sub">UNSAAC</div></div></div><nav class="nav">${navigation}</nav><div class="sidebar-foot"><div class="user-mini"><div class="avatar">${session.initials}</div><div><strong>${session.name}</strong><small>${session.label}</small></div></div><button class="logout" onclick="signOut()">Cerrar sesión</button></div></aside><main class="main"><header class="topbar"><div style="display:flex;gap:12px;align-items:center"><button class="icon-button mobile-menu" onclick="$('#sidebar').classList.toggle('open')">☰</button><h2>${title}</h2></div><div class="top-actions"><span class="badge info">2026-II</span></div></header><section class="content" id="view"></section></main></div>`;views[route]?.();}
function accessPending(){$('#app').innerHTML=`<main class="login-shell"><section class="login-brand"><div class="brand"><div class="seal">S</div><div><div class="brand-name">SIGMA OCRI</div><div class="brand-sub">UNSAAC</div></div></div><div class="hero"><div class="eyebrow">Solicitud recibida</div><h1>Tu cuenta está<br><span>pendiente.</span></h1><p>OCRI validará tu identidad institucional o universidad de origen antes de asignarte un rol.</p></div></section><section class="login-panel"><div class="login-box"><div class="eyebrow">Acceso restringido</div><h2>Cuenta registrada</h2><p>Se creó correctamente el perfil para <strong>${esc(session.email)}</strong>. Aún no tiene un rol habilitado, por lo que no puede acceder a los módulos.</p><div class="card"><div class="stat-label">Estado de la cuenta</div><div style="margin-top:12px">${badge(session.status)}</div></div><button class="btn btn-soft" style="margin-top:20px" onclick="signOut()">Cerrar sesión</button></div></section></main>`}
function go(r){route=r;render()}
const icons={dashboard:'▦',calls:'▤',sgms:'↗',sgme:'↙',nominations:'◎',documents:'□',reports:'▥',access:'⚙'};
function head(title,desc,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div>${action}</div>`}
function filteredApps(dir){let a=state.applications.filter(x=>x.direction===dir);if(session.role==='student')a=a.filter(x=>x.code==='193847');if(session.role==='external')a=a.filter(x=>x.code==='EXT-4491');if(session.role==='external_manager')a=a.filter(x=>session.university&&x.destination.includes(session.university));return a}
const views={
async access(){const view=$('#view');view.innerHTML=head('Administración de accesos','OCRI aprueba universidades y designa directamente a los gestores externos.')+'<div class="card">Cargando información de acceso…</div>';const [{data:universities,error:universityError},{data:profiles,error:profileError}]=await Promise.all([supabase.from('universities').select('id,name,country,is_unsaac,is_active,university_email_domains(email_domain,is_verified,is_active)').order('is_unsaac',{ascending:false}).order('name'),supabase.from('profiles').select('user_id,email,full_name,status,universities(id,name),user_roles!user_roles_user_id_fkey(roles(code,name))').order('created_at',{ascending:false})]);if(universityError||profileError){view.innerHTML=head('Administración de accesos','No fue posible cargar los datos.')+`<div class="card">${esc(universityError?.message||profileError?.message)}</div>`;return}accessProfiles=profiles;const externalUniversities=universities.filter(u=>!u.is_unsaac),managers=profiles.filter(p=>p.user_roles?.some(ur=>ur.roles?.code==='GESTOR_EXTERNO'));view.innerHTML=head('Administración de accesos','OCRI aprueba universidades y designa directamente a los gestores externos.',`<button class="btn btn-primary" onclick="universityModal()">+ Registrar universidad</button>`)+`<div class="grid-2"><div class="card"><div class="section-title"><h3>Universidades y dominios</h3><span class="badge info">${universities.length}</span></div>${universities.map(u=>`<div class="doc-item"><div class="doc-icon">UNI</div><div class="doc-main"><strong>${esc(u.name)}</strong><small>${esc(u.country||'Sin país')} · ${(u.university_email_domains||[]).map(d=>esc(d.email_domain)).join(', ')||'Sin dominio'}</small></div>${badge(u.is_active?'ACTIVA':'SUSPENDIDA')}</div>`).join('')}</div><div class="card"><h3>Designar gestor externo</h3><p class="muted">Escriba el correo institucional de la persona oficialmente designada.</p><form class="form-grid" onsubmit="designateExternalManager(event)"><div class="field wide"><label>Correo de la persona designada</label><input class="input" name="email" type="email" placeholder="encargado@universidad.edu" required></div><div class="modal-actions wide"><button class="btn btn-primary">Asignar GESTOR EXTERNO</button></div></form><h3 style="margin-top:28px">Gestores por universidad</h3>${externalUniversities.length?externalUniversities.map(u=>{const manager=managers.find(p=>p.universities?.id===u.id);return `<div class="doc-item"><div class="doc-icon">EXT</div><div class="doc-main"><strong>${esc(u.name)}</strong><small>${manager?esc(manager.full_name||manager.email)+' · '+esc(manager.email):'Sin gestor asignado'}</small></div>${manager?badge('ACTIVO'):badge('PENDIENTE')}</div>`}).join(''):'<p class="muted">Aún no hay universidades externas aprobadas.</p>'}</div></div>`},
dashboard(){const apps=state.applications, pending=apps.filter(x=>/REVISION|VALIDACION/.test(x.status)).length, observed=apps.filter(x=>x.status==='OBSERVADO').length, approved=apps.filter(x=>/APROBADO/.test(x.status)).length;if(session.role==='student'||session.role==='external'){const a=filteredApps(session.role==='student'?'SALIENTE':'ENTRANTE')[0];$('#view').innerHTML=head(`Hola, ${session.name.split(' ')[0]}`,'Revisa el avance de tu proceso de movilidad.')+`<div class="cards"><div class="card stat"><div class="stat-label">Estado actual</div><div style="margin:16px 0">${badge(a.status)}</div><div class="progress"><span style="width:${a.progress}%"></span></div></div><div class="card stat"><div class="stat-label">Avance del expediente</div><div class="stat-value">${a.progress}%</div><div class="stat-change">Actualizado recientemente</div></div><div class="card stat"><div class="stat-label">Documentos aprobados</div><div class="stat-value">${a.documents.filter(d=>d.status==='APROBADO').length}/${a.documents.length}</div></div><div class="card stat"><div class="stat-label">Observaciones</div><div class="stat-value">${a.documents.filter(d=>d.status==='OBSERVADO').length}</div></div></div>${applicationDetail(a)}`;return}$('#view').innerHTML=head('Panel institucional','Resumen operativo de movilidad académica al 7 de agosto de 2026.',`<button class="btn btn-soft" onclick="resetDemo()">Restablecer demo</button>`)+`<div class="cards"><div class="card stat"><div class="stat-label">Postulaciones totales</div><div class="stat-value">${apps.length}</div><div class="stat-change">Periodo 2026-II</div></div><div class="card stat"><div class="stat-label">Pendientes de revisión</div><div class="stat-value">${pending}</div><div class="stat-change">Requieren atención</div></div><div class="card stat"><div class="stat-label">Expedientes observados</div><div class="stat-value">${observed}</div></div><div class="card stat"><div class="stat-label">Aprobados OCRI</div><div class="stat-value">${approved}</div></div></div><div class="grid-2"><div class="card"><div class="section-title"><h3>Actividad reciente</h3><button class="btn btn-sm btn-soft" onclick="go('documents')">Revisar</button></div>${appTable(apps.slice(0,5))}</div><div class="card"><h3>Distribución de movilidad</h3><div class="bar-chart"><div class="bar-col"><div class="bar" style="height:140px"></div>Saliente</div><div class="bar-col"><div class="bar" style="height:92px"></div>Entrante</div><div class="bar-col"><div class="bar" style="height:50px"></div>Aprobada</div><div class="bar-col"><div class="bar" style="height:72px"></div>Revisión</div></div></div></div>`},
calls(){const canEdit=/admin/.test(session.role);$('#view').innerHTML=head('Convocatorias','Oportunidades y periodos de movilidad académica.',canEdit?`<button class="btn btn-primary" onclick="callModal()">+ Nueva convocatoria</button>`:'')+`<div class="filters"><select class="input" onchange="filterCards(this.value)"><option value="">Todas las direcciones</option><option>SALIENTE</option><option>ENTRANTE</option></select></div><div class="call-grid" id="callGrid">${state.calls.map(c=>callCard(c,canEdit)).join('')}</div>`},
sgms(){appView('SALIENTE','SGMS · Movilidad saliente','Postulaciones de alumnos UNSAAC hacia universidades de destino.')},
sgme(){appView('ENTRANTE','SGME · Movilidad entrante','Postulaciones de estudiantes externos hacia la UNSAAC.')},
nominations(){const action=session.role==='admin'?`<button class="btn btn-primary" onclick="nominationModal()">+ Registrar nominación</button>`:'';const nominations=session.role==='external_manager'?state.nominations.filter(n=>n.university===session.university):state.nominations;$('#view').innerHTML=head('Nominaciones',session.role==='external_manager'?`Nominaciones de ${session.university||'su universidad'}.`:'Estudiantes propuestos por universidades de origen.',action)+`<div class="card">${nomTable(nominations)}</div>`},
documents(){let apps=state.applications;if(session.role==='student')apps=filteredApps('SALIENTE');if(session.role==='external')apps=filteredApps('ENTRANTE');const docs=apps.flatMap(a=>a.documents.map((d,i)=>({...d,app:a,index:i})));$('#view').innerHTML=head('Gestión documental','Revisión individual, observaciones y trazabilidad de documentos.')+`<div class="card"><div class="doc-list">${docs.map(d=>`<div class="doc-item"><div class="doc-icon">PDF</div><div class="doc-main"><strong>${esc(d.name)}</strong><small>${d.app.id} · ${esc(d.app.student)}</small></div>${badge(d.status)}${/admin|reviewer/.test(session.role)?`<button class="btn btn-sm btn-soft" onclick="reviewModal('${d.app.id}',${d.index})">Revisar</button>`:''}</div>`).join('')}</div></div>`},
reports(){const faculties={};state.applications.forEach(a=>faculties[a.faculty]=(faculties[a.faculty]||0)+1);$('#view').innerHTML=head('Reportes','Indicadores consolidados y exportación de información.',`<button class="btn btn-primary" onclick="exportCSV()">Exportar CSV</button>`)+`<div class="cards"><div class="card stat"><div class="stat-label">Salientes</div><div class="stat-value">${filteredApps('SALIENTE').length}</div></div><div class="card stat"><div class="stat-label">Entrantes</div><div class="stat-value">${filteredApps('ENTRANTE').length}</div></div><div class="card stat"><div class="stat-label">Universidades</div><div class="stat-value">5</div></div><div class="card stat"><div class="stat-label">Países</div><div class="stat-value">4</div></div></div><div class="grid-2"><div class="card"><h3>Postulantes por facultad</h3>${Object.entries(faculties).map(([f,n])=>`<p>${f} <strong style="float:right">${n}</strong></p><div class="progress"><span style="width:${n*30}%"></span></div>`).join('')}</div><div class="card"><h3>Estado de expedientes</h3>${state.applications.map(a=>`<p style="display:flex;justify-content:space-between"><span>${a.id}</span>${badge(a.status)}</p>`).join('')}</div></div>`}
};
function appView(dir,title,desc){const apps=filteredApps(dir);const action=(session.role==='student'&&dir==='SALIENTE')||(session.role==='external'&&dir==='ENTRANTE')?`<button class="btn btn-primary" onclick="applicationModal('${dir}')">+ Nueva postulación</button>`:'';$('#view').innerHTML=head(title,desc,action)+`<div class="cards"><div class="card stat"><div class="stat-label">Total</div><div class="stat-value">${apps.length}</div></div><div class="card stat"><div class="stat-label">En proceso</div><div class="stat-value">${apps.filter(a=>!/APROBADO|FINALIZADO/.test(a.status)).length}</div></div><div class="card stat"><div class="stat-label">Observados</div><div class="stat-value">${apps.filter(a=>a.status==='OBSERVADO').length}</div></div><div class="card stat"><div class="stat-label">Aprobados</div><div class="stat-value">${apps.filter(a=>/APROBADO/.test(a.status)).length}</div></div></div><div class="card">${apps.length?appTable(apps):'<div class="empty">No hay postulaciones registradas.</div>'}</div>`}
function appTable(apps){return `<div class="table-wrap"><table class="table"><thead><tr><th>Expediente</th><th>Estudiante</th><th>Facultad</th><th>Universidad</th><th>Estado</th><th>Avance</th><th></th></tr></thead><tbody>${apps.map(a=>`<tr><td><strong>${a.id}</strong><br><small class="muted">${a.submitted}</small></td><td>${esc(a.student)}<br><small class="muted">${a.code}</small></td><td>${esc(a.faculty)}</td><td>${esc(a.destination)}</td><td>${badge(a.status)}</td><td><div class="progress" style="width:75px"><span style="width:${a.progress}%"></span></div></td><td><button class="btn btn-sm btn-soft" onclick="detailModal('${a.id}')">Ver</button></td></tr>`).join('')}</tbody></table></div>`}
function applicationDetail(a){return `<div class="grid-2"><div class="card"><h3>Documentos del expediente</h3><div class="doc-list">${a.documents.map(d=>`<div class="doc-item"><div class="doc-icon">PDF</div><div class="doc-main"><strong>${esc(d.name)}</strong><small>Documento requerido</small></div>${badge(d.status)}</div>`).join('')}</div></div><div class="card"><h3>Seguimiento</h3><div class="timeline">${a.history.map(h=>`<div class="timeline-item"><div class="timeline-dot"></div><div><strong>${esc(h[0])}</strong><p>${h[1]}</p></div></div>`).join('')}</div></div></div>`}
function callCard(c,edit){return `<article class="call-card" data-direction="${c.direction}"><div class="call-top"></div><div class="call-body">${badge(c.status)} <span class="badge neutral">${c.direction}</span><h3>${esc(c.title)}</h3><p class="muted">${esc(c.description)}</p><div class="call-meta"><span>◷ ${c.start} — ${c.end}</span><span>▦ Periodo ${c.period} · ${c.places} vacantes</span></div><div class="call-actions"><button class="btn btn-sm btn-soft" onclick="toast('Requisitos: PDF, récord y carta de motivación')">Ver requisitos</button>${edit?`<button class="btn btn-sm btn-danger" onclick="removeCall('${c.id}')">Eliminar</button>`:''}</div></div></article>`}
function nomTable(nominations=state.nominations){return `<div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Estudiante</th><th>Universidad</th><th>País</th><th>Contacto</th><th>Estado</th></tr></thead><tbody>${nominations.map(n=>`<tr><td><strong>${n.id}</strong></td><td>${esc(n.student)}</td><td>${esc(n.university)}</td><td>${esc(n.country)}</td><td>${esc(n.email)}</td><td>${badge(n.status)}</td></tr>`).join('')}</tbody></table></div>`}
function modal(body){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal">${body}</div></div>`)}function closeModal(){$('#modal')?.remove()}
function callModal(){modal(`<div class="modal-head"><h2>Nueva convocatoria</h2><button class="modal-close" onclick="closeModal()">×</button></div><form onsubmit="createCall(event)" class="form-grid"><div class="field wide"><label>Título</label><input class="input" name="title" required></div><div class="field"><label>Dirección</label><select class="input" name="direction"><option>SALIENTE</option><option>ENTRANTE</option></select></div><div class="field"><label>Periodo</label><input class="input" name="period" value="2027-I" required></div><div class="field"><label>Inicio</label><input class="input" type="date" name="start" required></div><div class="field"><label>Cierre</label><input class="input" type="date" name="end" required></div><div class="field"><label>Vacantes</label><input class="input" type="number" name="places" min="1" value="20"></div><div class="field wide"><label>Descripción</label><textarea class="input" name="description" required></textarea></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Guardar convocatoria</button></div></form>`)}
function createCall(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.calls.unshift({id:`C-${Date.now().toString().slice(-6)}`,...f,places:+f.places,status:'BORRADOR'});save();closeModal();render();toast('Convocatoria creada')}
function removeCall(id){if(!confirm('¿Eliminar esta convocatoria de demostración?'))return;state.calls=state.calls.filter(c=>c.id!==id);save();render();toast('Convocatoria eliminada')}
function filterCards(v){document.querySelectorAll('.call-card').forEach(e=>e.classList.toggle('hidden',v&&e.dataset.direction!==v))}
function detailModal(id){const a=state.applications.find(x=>x.id===id);modal(`<div class="modal-head"><div><h2>${a.id}</h2><span class="muted">${esc(a.student)}</span></div><button class="modal-close" onclick="closeModal()">×</button></div>${applicationDetail(a)}${/admin|reviewer/.test(session.role)?`<div class="modal-actions"><select id="appStatus" class="input"><option>EN_REVISION_DOCUMENTAL</option><option>OBSERVADO</option><option>APROBADO_OCRI</option><option>RECHAZADO</option><option>FINALIZADO</option></select><button class="btn btn-primary" onclick="changeAppStatus('${a.id}')">Actualizar estado</button></div>`:''}`)}
function changeAppStatus(id){const a=state.applications.find(x=>x.id===id),s=$('#appStatus').value;a.status=s;a.history.push([s.replaceAll('_',' '),new Date().toLocaleDateString('es-PE')]);a.progress=s==='APROBADO_OCRI'?100:a.progress;save();closeModal();render();toast('Estado actualizado y registrado')}
function reviewModal(id,index){const a=state.applications.find(x=>x.id===id),d=a.documents[index];modal(`<div class="modal-head"><h2>Revisar documento</h2><button class="modal-close" onclick="closeModal()">×</button></div><p><strong>${esc(d.name)}</strong><br><span class="muted">${a.id} · ${esc(a.student)}</span></p><div class="field"><label>Resultado</label><select class="input" id="docStatus"><option>APROBADO</option><option>OBSERVADO</option><option>RECHAZADO</option><option>EN_REVISION</option></select></div><div class="field" style="margin-top:14px"><label>Observación</label><textarea class="input" id="comment" placeholder="Detalle la observación si corresponde"></textarea></div><div class="modal-actions"><button class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary" onclick="saveReview('${id}',${index})">Registrar revisión</button></div>`)}
function saveReview(id,i){const a=state.applications.find(x=>x.id===id),s=$('#docStatus').value;a.documents[i].status=s;a.documents[i].comment=$('#comment').value;a.documents[i].reviewedBy=session.name;a.documents[i].reviewedAt=new Date().toISOString();if(s==='OBSERVADO')a.status='OBSERVADO';save();closeModal();render();toast('Revisión guardada con trazabilidad')}
function nominationModal(){modal(`<div class="modal-head"><h2>Registrar nominación</h2><button class="modal-close" onclick="closeModal()">×</button></div><form class="form-grid" onsubmit="createNomination(event)"><div class="field wide"><label>Estudiante</label><input class="input" name="student" required></div><div class="field"><label>Universidad de origen</label><input class="input" name="university" required></div><div class="field"><label>País</label><input class="input" name="country" required></div><div class="field wide"><label>Correo institucional</label><input class="input" type="email" name="email" required></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Enviar invitación</button></div></form>`)}
function createNomination(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.nominations.unshift({id:`NOM-${String(state.nominations.length+35).padStart(3,'0')}`,...f,status:'INVITACION_ENVIADA'});save();closeModal();render();toast('Nominación registrada')}
function applicationModal(dir){modal(`<div class="modal-head"><h2>Nueva postulación ${dir==='SALIENTE'?'saliente':'entrante'}</h2><button class="modal-close" onclick="closeModal()">×</button></div><form class="form-grid" onsubmit="createApplication(event,'${dir}')"><div class="field wide"><label>Convocatoria</label><select class="input" name="callId">${state.calls.filter(c=>c.direction===dir&&c.status==='ACTIVA').map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></div><div class="field"><label>Facultad</label><input class="input" name="faculty" required></div><div class="field"><label>${dir==='SALIENTE'?'Universidad destino':'Universidad de origen'}</label><input class="input" name="destination" required></div><div class="field wide"><label>Motivación / actividad académica</label><textarea class="input" required></textarea></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Guardar borrador</button></div></form>`)}
function createApplication(e,dir){e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),isOut=dir==='SALIENTE';state.applications.push({id:`${isOut?'SGMS':'SGME'}-${Date.now().toString().slice(-4)}`,direction:dir,student:session.name,code:isOut?'193847':'EXT-NEW',faculty:f.faculty,destination:f.destination,callId:f.callId,status:'BORRADOR',submitted:new Date().toISOString().slice(0,10),progress:15,documents:[{name:isOut?'DNI':'Pasaporte',status:'PENDIENTE'},{name:'Récord académico',status:'PENDIENTE'},{name:isOut?'Carta de motivación':'Carta de nominación',status:'PENDIENTE'}],history:[['BORRADOR',new Date().toLocaleDateString('es-PE')]]});save();closeModal();render();toast('Borrador creado')}
function exportCSV(){const rows=[['Expediente','Dirección','Estudiante','Facultad','Universidad','Estado','Fecha'],...state.applications.map(a=>[a.id,a.direction,a.student,a.faculty,a.destination,a.status,a.submitted])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='reporte-sigma.csv';a.click();URL.revokeObjectURL(a.href);toast('Reporte CSV generado')}
function resetDemo(){if(confirm('¿Restablecer todos los datos de la demostración?')){state=structuredClone(INITIAL);save();render();toast('Datos restablecidos')}}
function universityModal(){modal(`<div class="modal-head"><h2>Registrar universidad externa</h2><button class="modal-close" onclick="closeModal()">×</button></div><p class="muted">Ingrese el dominio oficial sin @; por ejemplo, universidad.edu.</p><form class="form-grid" onsubmit="createUniversity(event)"><div class="field wide"><label>Nombre de la universidad</label><input class="input" name="name" required></div><div class="field"><label>País</label><input class="input" name="country" required></div><div class="field"><label>Dominio institucional</label><input class="input" name="domain" placeholder="universidad.edu" required></div><div class="modal-actions wide"><button type="button" class="btn btn-soft" onclick="closeModal()">Cancelar</button><button class="btn btn-primary">Aprobar y registrar</button></div></form>`)}
async function createUniversity(event){event.preventDefault();const f=Object.fromEntries(new FormData(event.target));const {error}=await supabase.rpc('admin_create_university_with_domain',{university_name:f.name,university_country:f.country,institutional_domain:f.domain});if(error)return toast(error.message);closeModal();toast('Universidad y dominio aprobados.');views.access()}
async function designateExternalManager(event){event.preventDefault();const f=Object.fromEntries(new FormData(event.target)),person=accessProfiles.find(p=>p.email.toLowerCase()===f.email.trim().toLowerCase());if(!person)return toast('No existe una cuenta registrada con ese correo.');if(!person.universities||person.universities.name==='Universidad Nacional de San Antonio Abad del Cusco')return toast('La persona debe pertenecer a una universidad externa aprobada.');const {error}=await supabase.rpc('admin_set_user_role',{target_user_id:person.user_id,target_role_code:'GESTOR_EXTERNO'});if(error)return toast(error.message);toast('Gestor externo designado.');views.access()}
// Punto de entrada: restaura sesiones y reacciona a login, recuperación y cierre de sesión.
async function boot(){if(!supabase)return login();const {data:{session:authSession}}=await supabase.auth.getSession();if(authSession)await loadSession(authSession.user);else login();supabase.auth.onAuthStateChange(async(event,nextSession)=>{if(event==='PASSWORD_RECOVERY')passwordRecoveryMode=true;if((event==='SIGNED_IN'||event==='PASSWORD_RECOVERY')&&nextSession)await loadSession(nextSession.user);if(event==='SIGNED_OUT')login();});}
Object.assign(window,{$,signIn,requestPasswordReset,showRegister,register,setPassword,signOut,go,resetDemo,callModal,removeCall,filterCards,detailModal,changeAppStatus,reviewModal,saveReview,nominationModal,createNomination,applicationModal,createApplication,exportCSV,closeModal,universityModal,createUniversity,designateExternalManager});
boot();
